import { useState } from "react";
import { Bot, TrendingUp, TrendingDown, Clock, Target, Shield, CheckCircle2, AlertTriangle } from "lucide-react";

type SignalSide = "BUY" | "SELL";
type SignalStatus = "pending" | "executed" | "rejected" | "expired";

interface TradingSignal {
  id: string;
  timestamp: string;
  symbol: string;
  side: SignalSide;
  confidence: number;
  entryPrice: number;
  tpPrice: number;
  slPrice: number;
  lotSize: number;
  reason: string[];
  status: SignalStatus;
}

const mockSignals: TradingSignal[] = [
  {
    id: "SIG-001",
    timestamp: "2026-08-04T14:35:00Z",
    symbol: "XAUUSD",
    side: "BUY",
    confidence: 78,
    entryPrice: 2348.50,
    tpPrice: 2355.00,
    slPrice: 2344.00,
    lotSize: 0.1,
    reason: ["EMA bullish alignment", "RSI oversold recovery", "Support level bounce"],
    status: "pending",
  },
  {
    id: "SIG-002",
    timestamp: "2026-08-04T14:30:00Z",
    symbol: "XAUUSD",
    side: "SELL",
    confidence: 65,
    entryPrice: 2352.00,
    tpPrice: 2345.00,
    slPrice: 2356.50,
    lotSize: 0.15,
    reason: ["Resistance rejection", "Bearish divergence RSI", "Volume decline"],
    status: "pending",
  },
  {
    id: "SIG-003",
    timestamp: "2026-08-04T14:25:00Z",
    symbol: "XAUUSD",
    side: "BUY",
    confidence: 82,
    entryPrice: 2345.00,
    tpPrice: 2352.00,
    slPrice: 2340.00,
    lotSize: 0.1,
    reason: ["Golden cross confirmed", "MACD crossover", "Strong support holds"],
    status: "pending",
  },
];

export function SignalCard() {
  const [signals, setSignals] = useState<TradingSignal[]>(mockSignals);

  const handleExecute = (signalId: string, action: "execute" | "reject") => {
    setSignals((prev) =>
      prev.map((s) =>
        s.id === signalId
          ? { ...s, status: action === "execute" ? "executed" : "rejected" }
          : s
      )
    );
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 80) return "bg-emerald-500";
    if (confidence >= 60) return "bg-amber-500";
    return "bg-rose-500";
  };

  const getStatusBadge = (status: SignalStatus) => {
    switch (status) {
      case "pending":
        return <span className="text-amber-500">Pending</span>;
      case "executed":
        return <span className="text-emerald-500 flex items-center gap-1"><CheckCircle2 className="h-3.5 w-3.5" /> Executed</span>;
      case "rejected":
        return <span className="text-slate-500 flex items-center gap-1"><AlertTriangle className="h-3.5 w-3.5" /> Rejected</span>;
      case "expired":
        return <span className="text-slate-500">Expired</span>;
    }
  };

  return (
    <div className="space-y-4">
      <h3 className="font-semibold flex items-center gap-2">
        <Bot className="h-5 w-5 text-primary" />
        AI Trading Signals
      </h3>
      <p className="text-xs text-muted-foreground">Real-time signals generated by the AI trading engine</p>

      <div className="space-y-3">
        {signals.map((signal) => (
          <div key={signal.id} className={`rounded-xl border bg-card p-4 transition-all ${signal.status === "pending" ? "border-primary/30 shadow-md" : "opacity-60"}`}>
            <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
              {/* Signal Header */}
              <div className="flex items-start gap-3">
                <div
                  className={`flex h-10 w-10 items-center justify-center rounded-lg font-bold text-white ${
                    signal.side === "BUY" ? "bg-emerald-500" : "bg-rose-500"
                  }`}
                >
                  {signal.side === "BUY" ? <TrendingUp className="h-5 w-5" /> : <TrendingDown className="h-5 w-5" />}
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-semibold">{signal.symbol}</span>
                    <span
                      className={`inline-flex items-center rounded px-2 py-0.5 text-xs font-bold ${
                        signal.side === "BUY" ? "bg-emerald-500/10 text-emerald-500" : "bg-rose-500/10 text-rose-500"
                      }`}
                    >
                      {signal.side}
                    </span>
                    {signal.status === "pending" && (
                      <span className="inline-flex items-center rounded-full px-2 py-0.5 text-[10px] font-semibold bg-amber-500/10 text-amber-500">
                        Live
                      </span>
                    )}
                  </div>
                  <div className="mt-1 flex items-center gap-3 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1"><Clock className="h-3 w-3" /> {new Date(signal.timestamp).toLocaleTimeString()}</span>
                    <span className="flex items-center gap-1"><Target className="h-3 w-3" /> Confidence: {signal.confidence}%</span>
                  </div>
                </div>
              </div>

              {/* Status */}
              <div className="sm:self-center">
                {getStatusBadge(signal.status)}
              </div>
            </div>

            {/* Signal Details Grid */}
            <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
              <div className="rounded-lg border bg-muted/50 p-2">
                <p className="text-[10px] uppercase text-muted-foreground">Entry Price</p>
                <p className="font-mono font-semibold">${signal.entryPrice.toFixed(2)}</p>
              </div>
              <div className="rounded-lg border bg-emerald-500/5 p-2">
                <p className="text-[10px] uppercase text-emerald-600">Take Profit</p>
                <p className="font-mono font-semibold">${signal.tpPrice.toFixed(2)}</p>
              </div>
              <div className="rounded-lg border bg-rose-500/5 p-2">
                <p className="text-[10px] uppercase text-rose-600">Stop Loss</p>
                <p className="font-mono font-semibold">${signal.slPrice.toFixed(2)}</p>
              </div>
              <div className="rounded-lg border bg-muted/50 p-2">
                <p className="text-[10px] uppercase text-muted-foreground">Lot Size</p>
                <p className="font-mono font-semibold">{signal.lotSize}</p>
              </div>
            </div>

            {/* Confidence Bar */}
            <div className="mt-3">
              <div className="flex items-center justify-between text-xs">
                <span className="text-muted-foreground">Signal Confidence</span>
                <span className="font-semibold">{signal.confidence}%</span>
              </div>
              <div className="mt-1 h-2 overflow-hidden rounded-full bg-muted">
                <div
                  className={`h-full ${getConfidenceColor(signal.confidence)}`}
                  style={{ width: `${signal.confidence}%` }}
                />
              </div>
            </div>

            {/* Reason Tags */}
            {signal.reason.length > 0 && (
              <div className="mt-3 flex flex-wrap gap-1">
                {signal.reason.map((reason, index) => (
                  <span key={index} className="inline-flex items-center rounded px-2 py-0.5 text-[10px] font-medium bg-primary/10 text-primary">
                    <svg className="mr-1 h-2.5 w-2.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    {reason}
                  </span>
                ))}
              </div>
            )}

            {/* Action Buttons - Only for pending signals */}
            {signal.status === "pending" && (
              <div className="mt-4 flex flex-wrap gap-2">
                <button
                  onClick={() => handleExecute(signal.id, "execute")}
                  disabled={signal.confidence < 50}
                  className={`inline-flex flex-1 items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-semibold ${
                    signal.confidence >= 50
                      ? "bg-emerald-500 text-white hover:bg-emerald-500/90"
                      : "bg-slate-300 text-slate-500 cursor-not-allowed"
                  } disabled:opacity-50`}
                >
                  <Shield className="h-4 w-4" />
                  Execute Trade
                </button>
                <button
                  onClick={() => handleExecute(signal.id, "reject")}
                  className="inline-flex flex-1 items-center justify-center gap-2 rounded-lg border bg-card px-4 py-2.5 text-sm font-semibold hover:bg-muted"
                >
                  Reject
                </button>
              </div>
            )}

            {signal.status !== "pending" && (
              <div className="mt-4 rounded-lg border bg-muted/50 p-3 text-center">
                <p className="text-sm font-medium">{signal.status === "executed" ? "Trade Successfully Executed" : "Signal Rejected"}</p>
                <p className="text-xs text-muted-foreground mt-1">Action completed at {new Date().toLocaleTimeString()}</p>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Empty State */}
      {signals.filter(s => s.status === "pending").length === 0 && (
        <div className="rounded-xl border border-dashed p-12 text-center">
          <Bot className="mx-auto h-10 w-10 text-muted-foreground mb-2" />
          <p className="text-sm text-muted-foreground">No pending signals</p>
          <p className="text-xs text-muted-foreground mt-1">AI is monitoring the market for new opportunities</p>
        </div>
      )}

      {/* Quick Info */}
      <div className="rounded-xl border bg-card p-4">
        <h4 className="font-semibold text-sm mb-2">Execution Settings</h4>
        <div className="flex items-center gap-4 text-xs text-muted-foreground">
          <span className="flex items-center gap-1"><Shield className="h-3.5 w-3.5" /> Auto-execute enabled for confidence &gt; 75%</span>
          <span className="flex items-center gap-1"><Target className="h-3.5 w-3.5" /> Max lot: 0.3</span>
        </div>
      </div>
    </div>
  );
}
