import { Activity, Crosshair, ShieldCheck, Target } from "lucide-react";
import type { ActionableSignalPreview } from "@/data/precision-execution";

export function ActionableSignalCard({ signal }: { signal: ActionableSignalPreview }) {
  return <article className="relative overflow-hidden rounded-2xl border border-emerald-500/30 bg-slate-950 text-slate-100 shadow-xl shadow-emerald-950/10" aria-label="Actionable dark mode signal card">
    <div className="absolute -right-20 -top-24 h-56 w-56 rounded-full bg-emerald-500/10 blur-3xl" /><div className="relative grid lg:grid-cols-[minmax(260px,0.75fr)_minmax(0,1.25fr)]"><div className="border-b border-slate-800 p-6 lg:border-b-0 lg:border-r"><div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-emerald-400"><Activity className="h-4 w-4" /> Actionable signal</span><span className="rounded-full border border-amber-500/30 bg-amber-500/10 px-2.5 py-1 text-[9px] font-semibold text-amber-400">{signal.status}</span></div><p className="mt-7 font-mono text-sm text-slate-400">{signal.symbol}</p><h2 className="mt-1 text-4xl font-bold tracking-tight text-emerald-400">{signal.bias}</h2><div className="mt-5 inline-flex items-center gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 font-mono text-sm font-bold text-amber-400"><Crosshair className="h-4 w-4" /> {signal.orderType}</div><div className="mt-6"><div className="flex items-center justify-between text-[10px]"><span className="text-slate-400">Signal confidence</span><strong className="text-emerald-400">{signal.confidence}%</strong></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-emerald-500" style={{ width: `${signal.confidence}%` }} /></div></div></div><div className="p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3"><Metric label="Entry" value={signal.entry} tone="text-amber-400" /><Metric label="Stop loss" value={signal.stopLoss} tone="text-rose-400" /><div className="rounded-lg border border-slate-800 bg-slate-900/70 p-3"><p className="text-[9px] uppercase tracking-wider text-slate-500">Minimum RRR</p><p className="mt-1 font-mono text-lg font-bold text-emerald-400">1:{signal.minimumRiskReward.toFixed(2)}</p></div>{signal.targets.map((target, index) => <Metric key={target} label={`TP${index + 1}`} value={target} tone="text-emerald-400" />)}</div><div className="mt-4 rounded-xl border border-slate-800 bg-slate-900/50 p-4"><div className="flex items-center gap-2 text-xs font-semibold"><ShieldCheck className="h-4 w-4 text-emerald-400" /> Evidence stack</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{signal.evidence.map((evidence) => <span key={evidence} className="flex items-center gap-2 text-[10px] text-slate-400"><Target className="h-3 w-3 text-emerald-400" /> {evidence}</span>)}</div></div><p className="mt-4 text-right text-[9px] uppercase tracking-wider text-slate-500">Preview signal · no live execution</p></div></div>
  </article>;
}

function Metric({ label, value, tone }: { label: string; value: number; tone: string }) { return <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-3"><p className="text-[9px] uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-1 font-mono text-lg font-bold ${tone}`}>{value.toFixed(5)}</p></div>; }
