import { Flag, ShieldAlert, Target } from "lucide-react";
import type { TradeLevelsPreview } from "@/data/precision-execution";

export function StopLossTakeProfitPanel({ levels }: { levels: TradeLevelsPreview }) {
  return <article className="overflow-hidden rounded-xl border bg-card shadow-sm" aria-label="Stop loss and multi take profit panel">
    <div className="flex items-start gap-3 border-b p-5"><span className="rounded-lg bg-rose-500/10 p-2 text-rose-500"><Target className="h-4 w-4" /></span><div><h2 className="font-semibold">SL & multi-TP map</h2><p className="mt-0.5 text-xs text-muted-foreground">Mechanical protection and staged targets from the precision entry.</p></div></div>
    <div className="grid gap-5 p-5 lg:grid-cols-[minmax(240px,0.7fr)_minmax(0,1.3fr)]"><div className="rounded-xl border border-rose-500/30 bg-rose-500/5 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-rose-500"><ShieldAlert className="h-4 w-4" /> PRECISE STOP LOSS</div><p className="mt-4 font-mono text-3xl font-bold text-rose-500">{levels.stopLoss.toFixed(5)}</p><div className="mt-4 space-y-2 text-xs"><Row label="Entry" value={levels.entry.toFixed(5)} /><Row label="Zone low" value={levels.zoneBoundary.toFixed(5)} /><Row label="Safety buffer" value={`${levels.bufferPips} pips`} /><Row label="Risk distance" value={levels.riskDistance.toFixed(5)} /></div><p className="mt-4 border-t border-rose-500/20 pt-3 text-[10px] text-muted-foreground">Buy SL = ACR zone low minus mandatory 3-pip buffer.</p></div><div className="grid gap-3 sm:grid-cols-3">{levels.targets.map((target) => <div key={target.id} className="relative overflow-hidden rounded-xl border bg-background/60 p-4"><div className="absolute inset-x-0 top-0 h-1 bg-emerald-500" /><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-500"><Flag className="h-3.5 w-3.5" /> {target.id}</span><span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[9px] font-semibold text-emerald-500">1:{target.riskReward.toFixed(2)}</span></div><p className="mt-5 font-mono text-xl font-bold">{target.price.toFixed(5)}</p><p className="mt-2 text-[10px] leading-relaxed text-muted-foreground">{target.source}</p></div>)}</div></div>
  </article>;
}

function Row({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between gap-3"><span className="text-muted-foreground">{label}</span><strong className="font-mono">{value}</strong></div>; }
