import { ArrowUp, LockKeyhole, ShieldCheck } from "lucide-react";
import type { TrailingStopPreview } from "@/data/precision-execution";

const statusTone = { LOCKED: "bg-emerald-500 text-white", NEXT: "bg-amber-500 text-white", PROJECTED: "bg-muted text-muted-foreground" } as const;

export function TrailingStopVisualization({ trailing }: { trailing: TrailingStopPreview }) {
  const initial = trailing.steps[0]?.stopPrice ?? 0;
  const latest = trailing.steps[trailing.steps.length - 1]?.stopPrice ?? initial;
  return <article className="overflow-hidden rounded-xl border bg-card shadow-sm" aria-label="Dynamic trailing stop visualization">
    <div className="flex flex-col justify-between gap-3 border-b p-5 sm:flex-row sm:items-start"><div className="flex items-start gap-3"><span className="rounded-lg bg-sky-500/10 p-2 text-sky-500"><ShieldCheck className="h-4 w-4" /></span><div><h2 className="font-semibold">ACR trailing-stop path</h2><p className="mt-0.5 text-xs text-muted-foreground">Projected protection follows newly confirmed fresh zones.</p></div></div><span className="self-start rounded-full bg-sky-500/10 px-2.5 py-1 text-[10px] font-semibold text-sky-500">{trailing.mode}</span></div>
    <div className="p-5"><div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric label="Initial SL" value={initial} /><Metric label="Projected SL" value={latest} /><div className="rounded-lg border bg-emerald-500/5 p-3"><p className="text-[9px] uppercase tracking-wider text-muted-foreground">Protection gained</p><p className="mt-1 font-mono text-sm font-semibold text-emerald-500">+{(latest - initial).toFixed(5)}</p></div></div><div className="relative"><div className="absolute bottom-5 left-[15px] top-5 w-px bg-border sm:bottom-auto sm:left-5 sm:right-5 sm:top-[15px] sm:h-px sm:w-auto" /><div className="relative grid gap-4 sm:grid-cols-4">{trailing.steps.map((step, index) => <div key={step.id} className="grid grid-cols-[32px_1fr] gap-3 sm:block"><span className={`z-10 flex h-8 w-8 items-center justify-center rounded-full text-[10px] font-bold ${statusTone[step.status]}`}>{step.status === "LOCKED" ? <LockKeyhole className="h-3.5 w-3.5" /> : index + 1}</span><div className="rounded-lg border bg-background/80 p-3 sm:mt-3"><span className="text-[9px] font-semibold text-muted-foreground">{step.status}</span><p className="mt-1 text-xs font-semibold">{step.trigger}</p><p className="mt-2 font-mono text-sm font-bold text-sky-500">{step.stopPrice.toFixed(5)}</p><p className="mt-1 text-[9px] leading-relaxed text-muted-foreground">{step.detail}</p></div></div>)}</div></div><div className="mt-4 flex items-center gap-2 rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-3 text-[10px] text-muted-foreground"><ArrowUp className="h-4 w-4 shrink-0 text-emerald-500" /><span><strong className="text-foreground">One-way protection:</strong> a Buy trailing stop may only move higher and is never loosened.</span></div></div>
  </article>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border bg-background/70 p-3"><p className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value.toFixed(5)}</p></div>; }
