import { Crosshair, Ruler, ShieldCheck, Target } from "lucide-react";
import { Link } from "react-router";
import { preciseStopLossSignals, type StopLossSignalStatus } from "@/data/precise-stop-loss";

const statusTone: Record<StopLossSignalStatus, string> = {
  VALID: "bg-emerald-500/10 text-emerald-500",
  REVIEW: "bg-amber-500/10 text-amber-500",
  INVALID: "bg-rose-500/10 text-rose-500",
};

export function PreciseStopLoss() {
  const active = preciseStopLossSignals[0];
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><Link to="/precision-execution" className="mb-4 inline-flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground"><Crosshair className="h-3.5 w-3.5" /> Precision Execution</Link><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><Target className="h-4 w-4" /> Mechanical risk boundary</div><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">Precise stop loss signals</h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Validate XAUUSD protection levels against fresh ACR structure, broker digits, mandatory buffer, and account risk.</p></div><span className="rounded-full border border-emerald-500/30 bg-emerald-500/5 px-3 py-1.5 text-xs font-semibold text-emerald-500">{preciseStopLossSignals.filter((signal) => signal.status === "VALID").length} VALID SIGNAL</span></header>

    <section aria-label="Primary precise stop loss signal" className="overflow-hidden rounded-2xl border border-emerald-500/30 bg-slate-950 text-slate-100 shadow-xl"><div className="grid gap-px bg-slate-800 lg:grid-cols-[1.2fr_0.8fr]"><div className="bg-slate-950 p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[0.24em] text-amber-300">Active protection plan</p><h2 className="mt-2 font-mono text-2xl font-semibold">{active.symbol} · {active.direction}</h2><p className="mt-1 text-xs text-slate-400">{active.timeframe} · generated {new Date(active.generatedAt).toLocaleTimeString()}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusTone[active.status]}`}>{active.status} · {active.confidence}%</span></div><div className="mt-6 grid grid-cols-3 gap-3"><Level label="Entry" value={active.entry} /><Level label="Current" value={active.currentPrice} tone="text-amber-300" /><Level label="Stop loss" value={active.stopLoss} tone="text-rose-300" /></div><div className="relative mt-6 h-20 rounded-lg bg-slate-900"><span className="absolute inset-y-0 left-[18%] w-[28%] border-x border-emerald-400/50 bg-emerald-400/10" /><Marker label="SL" value={active.stopLoss} left="12%" tone="bg-rose-400" /><Marker label="Entry" value={active.entry} left="48%" tone="bg-emerald-400" /><Marker label="Market" value={active.currentPrice} left="82%" tone="bg-amber-300" /></div></div><aside className="bg-slate-950 p-6"><p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">Risk specification</p><div className="mt-4 grid grid-cols-2 gap-3"><Data label="Distance" value={`${active.distancePips.toFixed(1)} pips`} /><Data label="Buffer" value={`${active.bufferPips} pips`} /><Data label="Lot size" value={active.lotSize.toFixed(2)} /><Data label="Risk" value={`$${active.riskAmount.toFixed(2)} · ${active.riskPercent}%`} /></div><div className="mt-4 rounded-lg border border-emerald-400/20 bg-emerald-400/5 p-3"><p className="text-[9px] uppercase tracking-wider text-emerald-300">Fresh ACR zone</p><p className="mt-1 font-mono text-sm">{active.acrZone.low.toFixed(2)} - {active.acrZone.high.toFixed(2)}</p></div><ul className="mt-4 space-y-2">{active.reasons.map((reason) => <li key={reason} className="flex gap-2 text-xs text-slate-400"><ShieldCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-400" /> {reason}</li>)}</ul></aside></div></section>

    <section aria-label="Stop loss signal queue" className="rounded-xl border bg-card shadow-sm"><div className="flex items-start gap-3 border-b p-5"><span className="rounded-lg bg-primary/10 p-2 text-primary"><Ruler className="h-4 w-4" /></span><div><h2 className="font-semibold">Signal validation queue</h2><p className="mt-0.5 text-xs text-muted-foreground">Protection candidates remain non-executable until every structural and risk gate passes.</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b text-muted-foreground"><th className="px-5 py-2.5 font-medium">Signal</th><th className="px-3 py-2.5 font-medium">Entry</th><th className="px-3 py-2.5 font-medium">Stop loss</th><th className="px-3 py-2.5 font-medium">Distance</th><th className="px-3 py-2.5 font-medium">ACR zone</th><th className="px-3 py-2.5 font-medium">Risk</th><th className="px-5 py-2.5 text-right font-medium">Status</th></tr></thead><tbody>{preciseStopLossSignals.map((signal) => <tr key={signal.id} className="border-b last:border-0"><td className="px-5 py-3"><p className={`font-mono font-semibold ${signal.direction === "BUY" ? "text-emerald-500" : "text-rose-500"}`}>{signal.symbol} {signal.direction}</p><p className="mt-0.5 text-[10px] text-muted-foreground">{signal.timeframe}</p></td><td className="px-3 py-3 font-mono">{signal.entry.toFixed(2)}</td><td className="px-3 py-3 font-mono text-rose-500">{signal.stopLoss.toFixed(2)}</td><td className="px-3 py-3 font-mono">{signal.distancePips.toFixed(1)} pips</td><td className="px-3 py-3"><p className="font-mono">{signal.acrZone.low.toFixed(2)} - {signal.acrZone.high.toFixed(2)}</p><p className="mt-0.5 text-[9px] text-muted-foreground">{signal.acrZone.status}</p></td><td className="px-3 py-3 font-mono">{signal.riskPercent.toFixed(2)}%</td><td className="px-5 py-3 text-right"><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold ${statusTone[signal.status]}`}>{signal.status} · {signal.confidence}%</span></td></tr>)}</tbody></table></div></section>
  </div>;
}

function Level({ label, value, tone = "text-slate-100" }: { label: string; value: number; tone?: string }) { return <div><p className="text-[9px] uppercase tracking-wider text-slate-500">{label}</p><p className={`mt-1 font-mono text-xl font-semibold ${tone}`}>{value.toFixed(2)}</p></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-slate-900 p-3"><p className="text-[9px] uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value}</p></div>; }
function Marker({ label, value, left, tone }: { label: string; value: number; left: string; tone: string }) { return <span className="absolute top-2 -translate-x-1/2 text-center" style={{ left }}><span className={`mx-auto block h-3 w-1 rounded-full ${tone}`} /><span className="mt-1 block text-[8px] text-slate-500">{label}</span><span className="block font-mono text-[9px] text-slate-300">{value.toFixed(2)}</span></span>; }
