import { useEffect, useState } from "react";
import { ArrowLeft, BrainCircuit, RefreshCw } from "lucide-react";
import { Link } from "react-router";
import { terminalApi, type AutoSelectionStatus, type AutoTradeRunnerStatus } from "@/lib/trading-terminal-api";

export function StrategyAutoSelection() {
  const [data, setData] = useState<AutoSelectionStatus | null>(null);
  const [runner, setRunner] = useState<AutoTradeRunnerStatus | null>(null);
  const [error, setError] = useState<string | null>(null);
  const load = async () => {
    const [selectionResult, runnerResult] = await Promise.allSettled([terminalApi.selectionStatus("XAUUSD"), terminalApi.runnerStatus()]);
    if (selectionResult.status === "fulfilled") { setData(selectionResult.value); setError(null); }
    else if (runnerResult.status === "rejected") setError("Belum ada snapshot strategy selection dan runner tidak tersedia.");
    else { setData(null); setError("Belum ada snapshot strategy selection; menampilkan status runner terakhir."); }
    if (runnerResult.status === "fulfilled") setRunner(runnerResult.value);
  };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 5000); return () => window.clearInterval(timer); }, []);
  const selected = data?.candidates.find((candidate) => candidate.recommendation === "SELECTED");
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link to="/auto-trade" className="mb-4 inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft className="h-3.5 w-3.5" /> Auto Trade</Link><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.2em] text-primary"><BrainCircuit className="h-4 w-4" /> Live strategy selection <span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] tracking-normal text-emerald-500">MT5 DATA</span></div><h1 className="mt-2 text-2xl font-semibold sm:text-3xl">Adaptive strategy selection</h1><p className="mt-1 text-sm text-muted-foreground">Read-only view of the same strategy evaluation used by the runner.</p></div><button type="button" onClick={() => void load()} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs"><RefreshCw className="h-3.5 w-3.5" /> Refresh</button></header>
    {error && <ErrorBox message={error} />}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Symbol" value={data?.symbol || runner?.symbol || "--"} /><Metric label="Status" value={data?.status || (runner ? "RUNNER ONLY" : "LOADING")} /><Metric label="Strategy" value={data?.selectedStrategyId || runner?.selectedStrategyId || "--"} /><Metric label="Decision" value={runner?.lastDecision || "HOLD"} /><Metric label="Timeframe" value={data?.analysisTimeframe || runner?.timeframe || "--"} /></section>
    <section className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_360px]"><article className="rounded-xl border border-emerald-500/30 bg-emerald-500/5 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-emerald-500">Selected strategy</p><h2 className="mt-2 text-xl font-semibold">{selected?.name || data?.selectedStrategyId || runner?.selectedStrategyId || "No selected strategy"}</h2><p className="mt-2 text-sm text-muted-foreground">{data?.reason || runner?.decisionReason || runner?.message || "Waiting for live evaluation."}</p><div className="mt-5 grid gap-3 sm:grid-cols-4"><Value label="Score" value={selected ? `${selected.score}` : "--"} /><Value label="Confidence" value={selected ? `${selected.confidence}%` : "--"} /><Value label="Decision" value={runner?.lastDecision || "HOLD"} /><Value label="State" value={runner?.state || "--"} /></div></article><article className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Live market context</h2><dl className="mt-4 space-y-3 text-xs"><Row label="Regime" value={data?.marketContext.regime || "--"} /><Row label="Trend" value={data?.marketContext.trend || "--"} /><Row label="Volatility" value={data?.marketContext.volatility || "--"} /><Row label="Spread" value={data ? number(data.marketContext.spreadPips) + " pips" : "--"} /><Row label="Generated" value={data?.generatedAt ? new Date(data.generatedAt).toLocaleString() : "--"} /></dl></article></section>
    <section><h2 className="mb-3 font-semibold">Live candidates</h2><div className="space-y-3">{data?.candidates.map((candidate, index) => <article key={candidate.id} className="rounded-xl border bg-card p-5"><div className="flex items-start gap-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-muted font-mono text-xs">{index + 1}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{candidate.name}</h3><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold">{candidate.recommendation}</span><strong className="ml-auto font-mono">{candidate.score.toFixed(1)}</strong></div><p className="mt-2 text-xs text-muted-foreground">Confidence {candidate.confidence.toFixed(1)}%</p>{candidate.blockedBy && <p className="mt-2 rounded bg-rose-500/5 p-2 text-xs text-rose-500">{candidate.blockedBy}</p>}</div></div></article>)}{!data?.candidates.length && <Empty text="Belum ada evaluasi strategy." />}</div></section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-mono text-sm font-semibold">{value}</p></article>; }
function Value({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-background/70 p-3"><p className="text-[10px] uppercase text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value}</p></div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between border-b pb-2"><dt className="text-muted-foreground">{label}</dt><dd className="font-mono">{value}</dd></div>; }
function number(value: number | null | undefined) { return value == null || !Number.isFinite(value) ? "--" : value.toFixed(2); }
function ErrorBox({ message }: { message: string }) { return <div className="rounded-lg border border-rose-500/30 bg-rose-500/5 p-3 text-xs text-rose-500">{message}</div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>; }
